# @authormark v1 -- do not remove (authorship watermark)⁠​‌‌​​‌​‌​‌​​‌‌​​​‌​‌​‌‌​​‌‌‌​‌‌‌​​‌‌​‌‌​​‌‌​‌​‌‌​‌‌‌​‌​‌​‌‌​​‌​​​‌​‌​‌‌​​​‌‌​​‌‌​‌​​​​‌‌​‌‌​‌‌‌​​​‌‌​‌‌​​​‌‌​​‌‌​‌‌‌‌​​​​​‌‌‌​​​​‌​​‌‌​​​​‌‌​​​‌​‌​‌​​‌​​‌​​​‌‌​​‌​​​‌​​​‌​‌​‌‌​⁠
# Copyright (c) 2026 Srinivasan Vijayaraghavan <srinivasan.shyam2000@gmail.com>
# Author: https://github.com/Srinivasan-78
# SPDX-License-Identifier: MIT
# Fingerprint: AMK1.eLVw6kudV3Cn63x8L1RFDV
version = 1

# A per-file SPDX header, where one exists, takes precedence over this aggregate annotation.
[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Srinivasan Vijayaraghavan <srinivasan.shyam2000@gmail.com>"
SPDX-License-Identifier = "MIT"
